### ISSUE TITLE
Fehlermeldung beim Senden // WritePacketThreadException

### ISSUE THREAD

**Issue by schabil** [Toemsel/Network#10]
Hallo :)
ich bekommen wenn ich eine Klasse von meinem "Server" an meinem "Client" senden möchte die Fehlermeldung "WritePacketThreadException" und die TCP-Verbindung (über ConnectionFactory.CreateSecureClientConnectionContainer (S_IP, S_port, 2048); aufgebaut) bricht ab.

Problemklasse: 
` public class Nutzer2 : RequestPacket
    {
        public string id { get; set; }
        public string Nutzername { get; set; }
        public string Anzeigename { get; set; }
        //public byte[] Nutzerlogo { get; set; }
        public string Nutzerebene { get; set; }
        public string Passwort { get; set; }
        public string Bemerkung { get; set; }
        [PacketIgnoreProperty]
        public bool valide { get; set; }
        public Nutzer2()
        {
            this.Anzeigename = null;
            this.Passwort = null;
            this.id = null;
            this.Nutzername = null;
            this.Nutzerebene = null;
            this.Bemerkung = null;
            this.valide = false;
        }
    }`

Was aber dagegen problemlos funktioniert ist:
`public class chat_message : RequestPacket
    {
        public string _nachricht { get; set; }
                public chat_message()
        {

        }

        public chat_message(string temp)
        {
            this._nachricht = temp;
        }
        public string get_message()
        {
            return _nachricht;
        }
    }`

leider habe ich keine Idee woran das liegen könnte, bzw. wie ich den Fehler herausfinden kann

**Comment by Toemsel** [comment]
Lösche mal folgende Zeilen aus dem Konstruktor

```
            this.Anzeigename = null;
            this.Passwort = null;
            this.id = null;
            this.Nutzername = null;
            this.Nutzerebene = null;
            this.Bemerkung = null;

```

**Comment by schabil** [comment]
Auch das hilft leider nicht.

Habe ich irgendwie die Möglichkeit mitzuloggen, wo er genau aus der Bahn fliegt?

**Comment by schabil** [comment]
Ich hatte beiner 2. Klasse ebenfalls das gleiche Problem, da konnte ich jedoch feststellen wenn ich den Securemodus abschalte und den normalen benutze, es problemlos funktioniert

**Comment by Toemsel** [comment]
[Du kannst dir die Exceptions ausgeben lassen.](https://github.com/Toemsel/Network/issues/1) Werde versuchen dein Szenario nachzustellen.

**Comment by Toemsel** [comment]
Bug found. Gonna fix and update. Thanks for your feedback.

**Comment by Toemsel** [comment]
Bug fixed with last commit. Nuget package uploading in next 2 hours.

**Comment by Toemsel** [comment]
[Package available](https://www.nuget.org/packages/Network/6.1.0.3)
