### ISSUE TITLE
RSA won't work in the UI thread.

### ISSUE THREAD

**Issue by Toemsel** [Toemsel/Network#12]
Funny thing. In WPF Application (client) we have to start connection in a new thread or exception will happen on server side.

tried on new wpf project with same code as on console proejct.
https://pastebin.com/dHyDBePh
^ here is Client class code, its simple connection without any packet handler. New thread works for me.

**Comment by newbiedeveloper9** [comment]
https://github.com/newbiedeveloper9/NetworkLibraryIssue
Simple project where issue is reproduced

**Comment by Toemsel** [comment]
Bug has been fixed within the master branch, commit: https://github.com/Toemsel/Network/commit/9e42c02c0f16019adf322eb11ca853bfe40bcc59
