### ISSUE TITLE
CPU utilization by Network.Logging.NetworkLog

### ISSUE THREAD

**Issue by Serejka** [Toemsel/Network#2]
I'm using library for transferring large amounts of raw data and explicitly disabled logging for all connections by setting `Connection.EnableLogging` to false.
The problem is that profiler still shows great cpu consumption in `Network.Logging.NetworkLog.LogPacket` function. This happens because of `Log(tableOutPut.ToStringAlternative())` which allways calls `ToStringAlternative()` method (before checking `EnableLogging`).
Profiler data shows that the method uses about 50% of cpu.

**Comment by Toemsel** [comment]
Thanks for mentioning the issue. I will resolve that issue later this day.
