### ISSUE TITLE
Lib Refactoring - Readonly Fields

### ISSUE THREAD

**Issue by EnderRifter** [Toemsel/Network#24]
A lot of the fields in many classes are not marked readonly but assigned at instantiation and never touched again. An example would be Connection.requestResponseMap. Here it should never be reassigned (we would lose all registered response packets). Thus it should be clearly marked as such, with the 'readonly' keyword. In fact, all similar fields should also be marked with 'readonly'.

**Comment by Toemsel** [comment]
Agree. Please fix and create PR
