### ISSUE TITLE
Lib Refactoring - Object Initialiser Syntax

### ISSUE THREAD

**Issue by EnderRifter** [Toemsel/Network#26]
Throughout the library, objects are instantiated and their properties later edited on multiple lines before the object is even used. These can be converted to object initialiser syntax:
---
For example, Connection.cs.
Old style (More verbose):
```cs
readStreamThread = new Thread(ReadWork);
readStreamThread.Priority = ThreadPriority.Normal;
readStreamThread.Name = $"Read Thread {IPLocalEndPoint.AddressFamily.ToString()}";
readStreamThread.IsBackground = true;
```
New style (Less verbose):
```cs
readStreamThread = new Thread(ReadWork)
{
    IsBackground = true,
    Priority = ThreadPriority.Normal,
    Name = $"Read Thread {IPLocalEndPoint.AddressFamily.ToString()}"
}
```
The new syntax is cleaner and less verbose, so helps with readability. Also it looks pretty :)

**Comment by Toemsel** [comment]
hmm. Disagree. Autoproperties are nice, but shouldn't be used for essential initialization stuff.
