### ISSUE TITLE
Lib Refactoring - Partial Classes should use Partial Methods

### ISSUE THREAD

**Issue by EnderRifter** [Toemsel/Network#27]
When a partial class is declared, methods to be implemented elsewhere should be declared within the main class file as a partial method. 
---
This affects Connection.cs solely, as its the only partial class.
Declaration in Connection.cs (Old style):
```cs
internal void Init()
{
    InitAddons();
    ...
}
```
And in ConnectionAddons.cs (Old style):
```cs
private void InitAddons()
{
    ...
}
```

Declaration in Connection.cs (New style):
```cs
partial void InitAddons();

internal void Init()
{
    InitAddons();
    ...
}
```
And in ConnectionAddons.cs (New style):
```cs
partial void InitAddons()
{
    ...
}
```
New declaration would use a partial method to improve code understanding for newcomers and for people who are browsing the library. They would instantly know that the InitAddons method is declared in the partial class, rather than looking for it in vain in Connection.cs.

**Comment by Toemsel** [comment]
Agree. Please fix and create PR
