### ISSUE TITLE
StopTCPListener trying to access a disposed object

### ISSUE THREAD

**Issue by JoaoPaul54** [Toemsel/Network#33]
While running this code (only for testing purposes of course) I get a disposed object access on the StopTCPListener call. removing this calls makes the code run flawlessly (without stopping the listener of course)

#
        serverConnectionContainer = ConnectionFactory.CreateServerConnectionContainer(Constants.Ports.VenueTCPReceiverPort);

        serverConnectionContainer.ConnectionLost += (a, b, c) => Console.WriteLine($"{serverConnectionContainer.Count} {b.ToString()} Connection lost {a.IPRemoteEndPoint.Port}. Reason {c.ToString()}");
        serverConnectionContainer.ConnectionEstablished += ReceivedConnectionHandler;

        serverConnectionContainer.CloseTCPConnections(CloseReason.ServerClosed);
        serverConnectionContainer.StopTCPListener();

**Comment by Toemsel** [comment]
[Fix in master branch](https://github.com/Toemsel/Network/commit/174d25f0f4263c8892a1a6efea8d49fb44706abd)
