### ISSUE TITLE
ConnectionLost Example / Issue

### ISSUE THREAD

**Issue by tluyben** [Toemsel/Network#34]
In any trivial example, including the ones from the docs, if I have a client and server, both with ConnectionLost event handlers set, these are never called. If I kill the client with the server connected (which works fine and is sending data) or with the client connected and I kill the server, it just waits and nothing happens. Tested on Windows, Linux, Mac. Am I missing something? Is there a complete example showing where it works as for me the example for the docs does not show connection lost either when the client is gone.

**Comment by Toemsel** [comment]
Thanks for the report. Let me investigate. Maybe we broke something with our last version

**Comment by Toemsel** [comment]
Fixed with the new commit. NuGet is on its way. Thanks for the report.
https://github.com/Toemsel/Network/commit/699452612ba726c59f383f18aee3e6788035d43e
