### ISSUE TITLE
Disconecting a client and reconnecting it creates more than one connection

### ISSUE THREAD

**Issue by JoaoPaul54** [Toemsel/Network#35]
[Example test scripts.zip](https://github.com/Toemsel/Network/files/3191128/Example.test.scripts.zip)

Attached, there is some small scripts which reproduce the error.

Issues seems to be a listener of some sort which is not closed when it should which in turn, makes it create 2 connections instead of one when the client is reconnected.

**Comment by Toemsel** [comment]
Set `connection.AutoReconnect` to `false `and unsubscribe from all `ConnectionLost, ConnectionReceived` events within the ConnectionLost delegate.
