### ISSUE TITLE
ClientConnectionContainer modifies collection during iteration

### ISSUE THREAD

**Issue by Toemsel** [Toemsel/Network#36]
[stack_trace.txt](https://github.com/Toemsel/Network/files/3202798/stack_trace.txt)

**Comment by JoaoPaul54** [comment]
Any ETA for this fix. It's kind of a blocking issue for me.

**Comment by Toemsel** [comment]
Fixed with https://github.com/Toemsel/Network/commit/e1e5fffb42d92191e1ca4138f85c390413060c66
