### ISSUE TITLE
ReadPacketthreadException happening sometimes with hardcoded values

### ISSUE THREAD

**Issue by JoaoPaul54** [Toemsel/Network#40]
Using hard coded values, it is possible to get the exception. Does not happen all the time, far from it. But when it happen it usually breaks the operations.

[Testing.zip](https://github.com/Toemsel/Network/files/3225227/Testing.zip)

**Comment by JoaoPaul54** [comment]
On a side note, about 1 every 5 or 6 runs, one of the connection lost events does not happen. It seems completely random but might be worth investigating as well

**Comment by Toemsel** [comment]
Fixed with: https://github.com/Toemsel/Network/commit/c95bea78676beac2c7a04c4f785f47ef8cf2d36d
NuGet as pre-release: https://www.nuget.org/packages/Network/6.1.1.13-rc
