### ISSUE TITLE
Close event not called

### ISSUE THREAD

**Issue by Toemsel** [Toemsel/Network#41]
Example: https://github.com/Toemsel/Network/issues/40

**Comment by JoaoPaul54** [comment]
Just a small heads'up on this issue. No idea if it helps in any way.

The event that is not called on the example is, from my tests, always the one with the "VenueServerConnectionLostHandler".

I also saw something else happen although less common which is one of the connection events also not being called.

Where all these 5 outputs should exist:

Player Controller received new connection client-side
Venue received new connection server-side
Player Controller received a new connection server-side
Venue received new connection client-side
Player Controller Received Data

There was 2 times (in over 100 tests) where the "Venue received new connection client-side" output didn't happen.

Again, no idea if this helps in any way but thought it was worth sharing.

**Comment by Toemsel** [comment]
Seems like the TCP-Close request hasn't been sent. (Due to a socket shutdown, propably)

+-----------+---------------+----------------+----------------+--------------+
| Direction | Type          | Local          | ASCII          | Packet       |
+-----------+---------------+----------------+----------------+--------------+
| Outgoing  | TcpConnection | 127.0.0.1:1001 | ServerClosed? | CloseRequest |
+-----------+---------------+----------------+----------------+--------------+

+-----------+---------------+-----------------+----------------+--------------+
| Direction | Type          | Local           | ASCII          | Packet       |
+-----------+---------------+-----------------+----------------+--------------+
| Incoming  | TcpConnection | 127.0.0.1:64327 | ServerClosed? | CloseRequest |
+-----------+---------------+-----------------+----------------+--------------+

Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x840 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x3848 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x326c has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x443c has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x266c has exited with code 0 (0x0).
The thread 0x261c has exited with code 0 (0x0).
+-----------+---------------+-----------------+----------------+--------------+
| Direction | Type          | Local           | ASCII          | Packet       |
+-----------+---------------+-----------------+----------------+--------------+
| Outgoing  | UdpConnection | 127.0.0.1:64331 | ServerClosed? | CloseRequest |
+-----------+---------------+-----------------+----------------+--------------+

Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x30c8 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x428 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in System.dll
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
+-----------+---------------+-----------------+----------------+--------------+
| Direction | Type          | Local           | ASCII          | Packet       |
+-----------+---------------+-----------------+----------------+--------------+
| Incoming  | UdpConnection | 127.0.0.1:64330 | ServerClosed? | CloseRequest |
+-----------+---------------+-----------------+----------------+--------------+

Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x36ac has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x103c has exited with code 0 (0x0).
The thread 0x1f28 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x2440 has exited with code 0 (0x0).
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x1740 has exited with code 0 (0x0).
+-----------+---------------+-----------------+----------------+--------------+
| Direction | Type          | Local           | ASCII          | Packet       |
+-----------+---------------+-----------------+----------------+--------------+
| Outgoing  | UdpConnection | 127.0.0.1:64328 | ClientClosed? | CloseRequest |
+-----------+---------------+-----------------+----------------+--------------+

Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x2268 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x303c has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
The thread 0x19d8 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.ThreadAbortException' in System.dll
Exception thrown: 'System.Threading.ThreadAbortException' in Network.dll
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll
+-----------+---------------+-----------------+----------------+--------------+
| Direction | Type          | Local           | ASCII          | Packet       |
+-----------+---------------+-----------------+----------------+--------------+
| Incoming  | UdpConnection | 127.0.0.1:64329 | ClientClosed? | CloseRequest |
+-----------+---------------+-----------------+----------------+--------------+

**Comment by Toemsel** [comment]
Closing the socket x seconds after the actual "close" request, the issue isn't reproducible. Hence, it is a timing issue. There are two options

1. Close the connection (shutdown) and wait till the server has received the message, then actually close the socket
2. Send the close request and shutdown. There is a chance (around 10%) that the socket will be gone before the data has been sent. Thus, no event will be thrown. But, the other connection will realize that the connection is corrupt. (After the ping timeout) which will automatically invoke the lost event.

Therefore, both 1 and 2 do invoke the event. (Just with a different close-reason)

I will note that "issue" and consider a solution. Thanks for the report
