### ISSUE TITLE
How do I close the connection nicely?

### ISSUE THREAD

**Issue by Hulkstance** [Toemsel/Network#42]
If I do the following in the Client:

`tcpConnection.Close(Network.Enums.CloseReason.ClientClosed);`

it closes the connection but the connection remains there, you can see that in Process Hacker in Network tab. Any solution for this?

**Comment by Toemsel** [comment]
Does the server receive the close event?

**Comment by Toemsel** [comment]
Ok, I will invest the issue. What software do you use to filter running child threads?

**Comment by Hulkstance** [comment]
Code here:

`// Server
_serverConnectionContainer = ConnectionFactory.CreateServerConnectionContainer(1234, false);

_serverConnectionContainer.ConnectionLost += (a, b, c) => Console.WriteLine($"{a.IPRemoteEndPoint} disconnected. Reason: {c}.");
_serverConnectionContainer.ConnectionEstablished += connectionEstablished;

_serverConnectionContainer.Start();

private static void connectionEstablished(Connection connection, ConnectionType type)
{
	Console.WriteLine($"{connection.IPRemoteEndPoint} connected. Online: {_serverConnectionContainer.Count}.");

	connection.RegisterRawDataHandler("file", (rawData, con) =>
	{
		Console.WriteLine("Received file size: {rawData.Data.Length}");

		connection.SendRawData("file_received", Encoding.UTF8.GetBytes("Hello from Server. File was received."));
	});

	connection.RegisterRawDataHandler("message", (rawData, con) => {
		Console.WriteLine("Received message: {rawData.ToUTF8String()}");
	});
}

// Client code
ConnectionResult connectionResult = ConnectionResult.TCPConnectionNotAlive;
TcpConnection tcpConnection = ConnectionFactory.CreateTcpConnection("127.0.0.1", 1234, out connectionResult);

if (connectionResult == ConnectionResult.Connected)
{
	tcpConnection.SendRawData("file", File.ReadAllBytes(path));
	tcpConnection.SendRawData("message", Encoding.UTF8.GetBytes("Hello, Server!"));

	tcpConnection.RegisterRawDataHandler("file_received", (rawData, con) =>
	{
		string serverMessage = rawData.ToUTF8String();

		tcpConnection.Close(Network.Enums.CloseReason.ClientClosed);
	});
}`

**Comment by Hulkstance** [comment]
I debugged it and seems to be ` invokePacketThread.AbortSave();` throwing ThreadAbortException.

In `InvokeWork()`, you can see that it received the CloseRequest but it fails to abort the thread at `HandleDefaultPackets(toDelegate);` and later in `ExternalClose(closeRequest.CloseReason);`.

**Comment by Toemsel** [comment]
Thanks for the invest. While trying to resolve the issue, I encountered that .NET Core doesn't support Thread.Abort. Besides switching completely to a task related behaviour, I try to find a workaround.

**Comment by Hulkstance** [comment]
No problem.

**Comment by Toemsel** [comment]
I wasn't able to find any remaining threads after closing the connection.
On .NET 4.6 > and >.NET Core the AbortSave() does abort the network threads successfully.
Maybe you didn't set "AutoReconnect" to false, in order to prevent  a reconnection?

Thread.ResetAbort() isn't a solution, since it aborts the abortion.

Please add some screenshots, highlighting the remaining threads. Or, even better, provide an example illustrating the issue.

**Comment by AntonVonDelta** [comment]
This is a real issue. My app is not working. The connection remains and even tieouts and appears as a different message when debugging(because it timeouts further in time). Is there a fix for this?

**Comment by Toemsel** [comment]
.NET or .NET Core?

Can you provide a minimalistic example?

**Comment by Toemsel** [comment]
maybe related to #53

**Comment by Toemsel** [comment]
Releated to https://github.com/Toemsel/Network/issues/55
