### ISSUE TITLE
Question about key

### ISSUE THREAD

**Issue by dretax** [Toemsel/Network#47]
If i want to send a rawdata to a completely different server which doesnt use this library, do I hve to give a key? Should i make it an empty string?

**Comment by Toemsel** [comment]
By "key" you are refering to the RSA public/private key encryption parameter?

I am sorry to inform you, that the library has several internal procedures which aren't compatible with other libraries out of the box. The library doesn't support a raw tcp/udp-stream yet.

If you plan to use this library, you would have to use it on the client- and server-side for a functioning  workflow.

**Comment by dretax** [comment]
Yeah I saw that. For that usage I have returned to my original use, for a different project I'll use this.
