### ISSUE TITLE
Assembly doesnt exist when deploying on Android device 

### ISSUE THREAD

**Issue by luky92** [Toemsel/Network#49]
The app that works perfectly when deployed on emulator but when deployed on device the connection closes with assembly doesnt exist error Note the packets are defined in the external lib both Android app and windows form server app reference tested both Net framework clasic lib and net standard lib but it doesn't work

**Comment by luky92** [comment]
Looks like the device sends empty assembly name in the registration packet investigating to figure out why

**Comment by luky92** [comment]
the cast in `d HandleDefaultPackets(Packet packet)` seems to be failing

**Comment by Toemsel** [comment]
Please provide a minimalistic example project illustrating the issue.

**Comment by luky92** [comment]
https://drive.google.com/file/d/1FtM_K6SwtoGYE6Nf8dNxH8MUJjNARtjy/view?usp=sharing here is the striped down version just run the server app and android project remember to change ip

**Comment by Toemsel** [comment]
Please consider that you have personal information + licence keys within your provided example.
I did already download the example. You can take it offline any time.

**Comment by luky92** [comment]
thanks for info :) removed

**Comment by Toemsel** [comment]
![image](https://user-images.githubusercontent.com/6334140/67591033-ba876c80-f75c-11e9-8526-67dbe05ee2d4.png)

There is no issue within the network lib. Please consider following points

- Check the consolidated packages within the NuGet explorer. Make sure, that the server and client do have the same assemblies installed.
![image](https://user-images.githubusercontent.com/6334140/67591091-e4409380-f75c-11e9-858e-2694b9d4b91e.png)
- Your client does use RSA or the default ConnectionContainer. However, your server always uses the default ServerConnectionContainer, without RSA.

![image](https://user-images.githubusercontent.com/6334140/67591145-05a17f80-f75d-11e9-82bc-cfd4e76bd519.png)

![image](https://user-images.githubusercontent.com/6334140/67591163-10f4ab00-f75d-11e9-9eb3-e77529da894f.png)

Hence, on the emulator the client and server use the default config, without RSA.
On your device, the client uses RSA and the server no RSA. That isn't compatible.

I would suggest, that you use pre-compile statements to switch between RSA and none RSA containers. E.g.:

#if DEBUG
  .ClientConnectionContainer(..); ServerConnectionContainer(...)

#if !DEBUG
  .SecureClientConnectionContainer(); SecureServerConnectionContainer();

That way you only have to switch between Debug and release to enable RSA.

**Comment by luky92** [comment]
yep you are right sorry fo bodering and thank you for your help
