### ISSUE TITLE
how to get messge from server to client?

### ISSUE THREAD

**Issue by red-gezi** [Toemsel/Network#50]
when i send a message it will trigger InvokePacketThreadException,what should i do?

**Comment by red-gezi** [comment]
![YH2Z B6~DSQR$74519V2`K](https://user-images.githubusercontent.com/18701431/68922927-e9bb5780-07b7-11ea-90bb-58042483f13f.png)

**Comment by Toemsel** [comment]
Could you please provide a minimalistic project setup and share it online? Then I would be able to debug into the issue. Thanks

**Comment by Toemsel** [comment]
I did build an example project for your special case.

![image](https://user-images.githubusercontent.com/6334140/68997174-cbcb2100-08a3-11ea-92dc-b285dabb4ee2.png)

[#50.zip](https://github.com/Toemsel/Network/files/3854526/50.zip)

Hope that helps you to build up your application.

**Comment by red-gezi** [comment]
Thanks very much
