### ISSUE TITLE
Compiling w/o supporting .net 3.5

### ISSUE THREAD

**Issue by Ziden** [Toemsel/Network#51]
Hello

So after compiling a .net 4.7.2 project it seems the bluetooth dependency compiles 2 libraries in .net 3.5 - InTheHand.dll and InTheHand.Devices.Bluetooth.Dll

Is it possible to remove the bluetooth dependency ? In this case its a project that will not run well in 3.5, its a Unity3D project.

We trying to import the network library inside Unity.

Thanks alot for any attention

**Comment by Toemsel** [comment]
Did you try to compile it against .NET Core? The .NET Core build excludes the bluetooth functionallity. Exactly what you need.

In case .NET core isn't supported within Unity, you could simply remove all bluetooth related information out of the source code. (Marked with #if NET46) Then you would have to compile it by your own. Shouldn't be that much work :)

**Comment by Toemsel** [comment]
I went ahead and did the work for you. There is a new branch for a none-bluetooth version.
https://github.com/Toemsel/Network/tree/master_no_bluetooth
