### ISSUE TITLE
Timeout Bug

### ISSUE THREAD

**Issue by toxicscams** [Toemsel/Network#61]
if i am trying to send a big byte array(3 mb) using connection.SendRawData(key, data[]); the client is disconnecting for the reason timeout

**Comment by Toemsel** [comment]
yeah, because of the keep alive packet.

Disable keep alive or adjust the timeout.

**Comment by toxicscams** [comment]
if i disable keep alive packet wouldn't it affect the client side if the server randomly crashed?

**Comment by toxicscams** [comment]
> yeah, because of the keep alive packet.
> 
> Disable keep alive or adjust the timeout.

i disabled the keep alive packet then after the byte array is received on the client side i am disconnecting for timeout

**Comment by Toemsel** [comment]
There is no option currently to transmit huge data packages. I will keep it in mind for future features.
