### ISSUE TITLE
Does this work on mobile devices using Unity?

### ISSUE THREAD

**Issue by asusralis** [Toemsel/Network#62]
And would aot matter at all?

**Comment by Toemsel** [comment]
It works with Unity and I see no reason why it shouldn't work for mobile devices as well.
AOT (iOS) has never been tested. Feel free to report your experience.

**Comment by asusralis** [comment]
Cool, thanks for the information! I'll definitely create an issue if there is any problems with aot. I've seen some network libraries require source files for #ifs specifically for unity/mobile, so I wasn't sure if this was the same case.
