### ISSUE TITLE
Uncatchable SocketException

### ISSUE THREAD

**Issue by skaupper** [Toemsel/Network#66]
Starting a server connection on a socket that is already taken by another process causes `ServerConnectionContainer.StartTCPListener` to throw a `SocketException`. 

Due to `StartTCPListener` being `async void` this exception cannot be handled by calling code and leads inevitably to a crash.

**Comment by Toemsel** [comment]
Fixed with https://github.com/Toemsel/Network/commit/a0e417bce878ca404c3d297611d6d39b663ea566.
NuGet won't be created for that issue. Wait for a new NuGet or use the SRC instead.
