### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by aidenpearce79** [Toemsel/Network#67]
### 'udpConnection' parameter is not used
https://github.com/Toemsel/Network/blob/8c135fb280452f053a942b9e68063c2dca313c36/Network/RSA/SecureClientConnectionContainer.cs#L32-L36

### Currently on my branch callstack:
https://github.com/aidenpearce79/Network/commit/b651019de90cf5f85d90a38e1381c3fb6e069fc5
```
internal SecureClientConnectionContainer(TcpConnection tcpConnection, UdpConnection udpConnection, RSAPair rsaPair)
            : base(tcpConnection, udpConnection)

internal ClientConnectionContainer(TcpConnection tcpConnection, UdpConnection udpConnection)
            : this(tcpConnection.IPRemoteEndPoint.Address.ToString(), tcpConnection.IPRemoteEndPoint.Port)
        
internal ClientConnectionContainer(string ipAddress, int port) : base(ipAddress, port) => ReconnectInterval = 2500;
```
Was it on purpose or was it a typo?

**Comment by Toemsel** [comment]
thanks for the info. There was a flaw within the lib itself. The connections weren't used at all.

**Comment by Toemsel** [comment]
Fixed with https://github.com/Toemsel/Network/commit/cb020779dbaded166faadb51e93546087633cb91
