### ISSUE TITLE
An example is needed

### ISSUE THREAD

**Issue by aidenpearce79** [Toemsel/Network#70]
1) How to create ClientConnectionContainer, without an asynchronous, events, etc. 

```
private static readonly ClientConnectionContainer _container;

static MyService() {
   _container = CreateClientConnectionContainer("...", 7777);

>    // What i need do here for container initialized/connected without async/await, events (like CreateTcpConnection(...))?
>    // It is correct to immediately send a request here (not in the constructor of course, after this point in GetTickets() for example)

}
```

2) What is the correct way to synchronously send packets in parallel use ClientConnectionContainer with the ability of receive a response?

```
public static TicketsResponse GetTickets(int id) {
   var response =   _container.SendAsync<TicketsResponse>(new TicketsRequest(id))....; 

> // .GetAwaiter().GetResult()?
> // .Result?
> // Wrap to Task.Run with local variable? How get response synchronously without async/await, events, etc.?

   return response;
}
```
Client code:
```
static void Main() {
   Parallel.For(0, 100, (i)=>{
      var response = MyService.GetTickets(i);
      if (response.Succes) {
         ...
      }
   });
}
```

Please add or give link to complex sample with that requirements, or just kick me in the right direction ))

**Comment by mblenczewski** [comment]
Should be solved with https://ptb.discordapp.com/channels/502989126916898837/502989127499776009/741652033483964446

**Comment by Toemsel** [comment]
> 1. How to create ClientConnectionContainer, without an asynchronous, events, etc.

The network is async and event driven. However, if you like a synchronous behaviour, you could "misapply" the TAP pattern. As an example:

```
            TcpConnection tcpConnection = ConnectionFactory.CreateTcpConnection("...", xxx, out ConnectionResult tcpRes);
            UdpConnection udpConnection = ConnectionFactory.CreateUdpConnection(tcpConnection, out ConnectionResult udpRes);
            ClientConnectionContainer container = ConnectionFactory.CreateClientConnectionContainer(tcpConnection, udpConnection);
```

If you take a closer look to "CreateTcpConnection" and "CreateUdpConnection" within the factory, both are actually async, but the execution won't be asynchronous, but synchronous. (Compared to CreateTcpConnectionAsync)

> 2. What is the correct way to synchronously send packets in parallel use ClientConnectionContainer with the ability of receive a response?

`container.SendAsync<TicketsResponse>(new TicketsRequest(id), ConnectionType.TCP).Result;`

**Comment by Toemsel** [comment]
Please contact if the issue hasn't be resolved yet.
