### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by blockplacer** [Toemsel/Network#72]
I liked that library so much but we are developing an video game which you know video games aren't susposed to disclosed they are closed source. So Gpl v3 requires disclosing source code. Please switch to MIT license.

**Comment by Toemsel** [comment]
The license model won't be changed. If you send me over some more details regarding your project, I might hand out a custom license to be used for your project.

**Comment by blockplacer** [comment]
Its an project featuring online sandbox worlds.
Users can build new areas and fight, play ,live and build.
That Library was perfect choice of our indie game project.
Its easy to use and makes job easier.

Also network library we used will be credited i liked that library so much that i never seen this level of easy of use network library .

**Comment by Toemsel** [comment]
Without any further do, just use it. You have my permission to modify/distribute/sell and keep it closed source, as long as it doesn't surpass your indie-game project. Please send me a link to your project, or if not yet existing, inform us when available :) Looking forward to it

**Comment by blockplacer** [comment]
thanks a lot your library was so good. just asking though can i use this library on multiple projects but not all of them commerical few one of them closed source but free game will be free too just featuring online servers having in game purchases. but if you make an premium version of that library i would defintiely spend money on it

**Comment by Toemsel** [comment]
As LGPL states, you dont have to open up your source, nor pay license fees, as long as you do not modify the library. If you reach the point that you modify the source, you have to publish the changes as well. That doesn't comprise your software product. Please see https://github.com/Toemsel/Network/blob/master/LICENSE

**Comment by blockplacer** [comment]
so using library with closed source commerical program isn't probem until i modify library.note: i would share any changes i made to library if i do something and change it.
Also seems to be lgpl requires software need include their license.

**Comment by Toemsel** [comment]
> so using library with closed source commerical program isn't probem until i modify library.note: i would share any changes i made to library if i do something and change it.

yes

> Also seems to be lgpl requires software need include their license.

All you need to to is adding a credit to that library.

**Comment by blockplacer** [comment]
thanks.
