### ISSUE TITLE
Calling ServerConnectionContainer.Stop or ServerConnectionContainer.StopTcpListener() Throws an Exception

### ISSUE THREAD

**Issue by Abdelfattah-Radwan** [Toemsel/Network#81]
Calling either `ServerConnectionContainer.Stop()` or `ServerConnectionContainer.StopTcpListener()` throws the following error: `An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in System.Private.CoreLib.dll
The I/O operation has been aborted because of either a thread exit or an application request.`

Using in a .NET 5 WPF application.

**Comment by Toemsel** [comment]
Fixed https://github.com/Toemsel/Network/commit/16ec8da0e3bb89948dc6ee5ed568e2702d92a9cb
