### ISSUE TITLE
Cannot communicate withe IPv4 address

### ISSUE THREAD

**Issue by Nic-Alexander** [Toemsel/Network#82]
I'm really impressed with your tools.   I'm not sure if this is the right place for a question like this.

I have set up the demo code, and it works fine if I use my computer's temporary IPv6 address for client and server, but if I set the client and the server to my computer's IPv6 address or its static IPv4 address (e.g. 192.168.1.150), then I get a client timeout error when it tries to create a connection.   I can ping the server from the client with any of the 3 addresses.

I can't find an example of setting the serve to an IPv4 address.   I have been using

      serverConnectionContainer = ConnectionFactory.CreateServerConnectionContainer(ipv4address, 1234, false);

Do you have any ideas what could be going wrong?

**Comment by Toemsel** [comment]
is the target port 1234 open on the target machine?

**Comment by Nic-Alexander** [comment]
Yes, the demo works fine with that port if I use the server's temporary IPv6 address.

**Comment by Toemsel** [comment]
Are you sure about this code?

  serverConnectionContainer = ConnectionFactory.CreateServerConnectionContainer(ipv4address, 1234, false);

The server doesn't need an IP. The client requires to point to the SVR ip.

**Comment by Nic-Alexander** [comment]
Ah; that was it!   The client now connects on the IPv4 address.   Thanks very much.
