### ISSUE TITLE
not sure what i'm missing when using the registerstaticpacket handler

### ISSUE THREAD

**Issue by JustAnotherGameDevWasTaken** [Toemsel/Network#86]
![errorcode](https://user-images.githubusercontent.com/89107810/159210847-e7303d31-8e61-4997-85e5-3ca941d4c81a.png)
"The type 'Networking_Test.Test' cannot be used as type parameter 'T' in the generic type or method 'Connection.RegisterStaticPacketHandler<T>(PacketReceivedHandler<T>)'. There is no implicit reference conversion from 'Networking_Test.Test' to 'Network.Packets.Packet'." is the error. i've clearly missed something, but i'm not sure what.

**Comment by Toemsel** [comment]
Check out the [examples](https://github.com/Toemsel/Network/tree/main/Examples)
