### ISSUE TITLE
AssemblyDoesNotExist when sending strings

### ISSUE THREAD

**Issue by JustAnotherGameDevWasTaken** [Toemsel/Network#88]
both  client and server have the System library in the project. code below:

called on client after connection:
 connection.RegisterStaticPacketHandler<Common_Packets.Test2>(Testing2);
 connection.Send(new Common_Packets.Test("Hello"));

called on server after connection:
 Console.WriteLine($"{connectionType} Connection received {connection.IPRemoteEndPoint}.");
 connection.RegisterStaticPacketHandler<Common_Packets.Test>(Testing);

both have these as packets: 
![Screenshot 2022-04-06 224319](https://user-images.githubusercontent.com/89107810/162076812-d159c345-860e-4d3f-9d2b-f5129d0326f2.png)

**Comment by JustAnotherGameDevWasTaken** [comment]
``

**Comment by Toemsel** [comment]
Can you provide a minimal example project?

**Comment by Toemsel** [comment]
No response received.
