### ISSUE TITLE
System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.'

### ISSUE THREAD

**Issue by rizwan1239** [Toemsel/Network#90]
I am getting this error on server side when I am trying to send this data from Unity by importing this network library in Unity.

Client:
`tcpConnection.SendRawData("HelloWorld", Encoding.UTF8.GetBytes("Hello, this is the RawDataExample!"));`

Server:
`connection.RegisterRawDataHandler("HelloWorld", (rawData, con) => Console.WriteLine($"RawDataPacket received. Data: {rawData.ToUTF8String()}"));
`

**Comment by Toemsel** [comment]
Were you able to solve the issue?
